'use strict';
let D;let view='financeiro';const state={start:'2026-07-27',end:'2026-09-24',ad:'',broker:'',status:'',query:'',review:'',financeStart:'2026-03-01',financeEnd:'2026-12-31',campaign:''};
const $=s=>document.querySelector(s), esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const num=v=>new Intl.NumberFormat('pt-BR',{maximumFractionDigits:0}).format(v),money=v=>v===null?'—':new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(v),pct=v=>v===null?'—':new Intl.NumberFormat('pt-BR',{style:'percent',maximumFractionDigits:1}).format(v),day=s=>s?s.split('-').reverse().join('/'):'—';
const sum=(rs,k)=>rs.reduce((s,r)=>s+(Number(r[k])||0),0),unique=a=>[...new Set(a)],ratio=(a,b)=>b?a/b:null;
const high=l=>!l.excluded&&(/pronto|30 dias|entre 1 e 3 meses/i.test(l.term)),cat=l=>l.excluded?'Fora do perfil':high(l)?(/30 dias|pronto/i.test(l.term)?'Imediata':'1 a 3 meses'):/pesquisando/i.test(l.term)?'Pesquisando':'Não classificado';
const selected=()=>D.leads.filter(l=>l.date>=state.start&&l.date<=state.end&&(!state.ad||l.adId===state.ad));
const media=()=>D.meta.filter(l=>l.date>=state.start&&l.date<=state.end&&(!state.ad||l.adId===state.ad));
const badge=(s,type='')=>'<span class="badge '+type+'">'+esc(s)+'</span>';
const card=(label,value,note,primary=false)=>'<div class="kpi '+(primary?'primary':'')+'"><label>'+label+'</label><strong>'+value+'</strong><small>'+note+'</small></div>';
const panel=(title,sub,body)=>'<section class="panel"><div class="panelhead"><div><h2>'+title+'</h2><p>'+sub+'</p></div></div>'+body+'</section>';
const table=(headers,rows)=>'<div class="tablewrap"><table><thead><tr>'+headers.map((h,i)=>'<th>'+h+'</th>').join('')+'</tr></thead><tbody>'+(rows.length?rows.map(r=>'<tr>'+r.map(c=>'<td>'+c+'</td>').join('')+'</tr>').join(''):'<tr><td colspan="'+headers.length+'" class="empty">Nenhum registro para os filtros selecionados.</td></tr>')+'</tbody></table></div>';
const options=(a,current)=>'<option value="">Todos</option>'+a.map(([v,t])=>'<option value="'+esc(v)+'" '+(v===current?'selected':'')+'>'+esc(t)+'</option>').join('');
function filterUI(){
let html='';
if(view==='financeiro'&&financialTab==='previsao'){html='<span class="smallnote">Previsão · próximos 12 meses</span>';}else if(view==='financeiro'||view==='historico'){html='<label>Período · de<input type="date" min="2026-03-01" data-key="financeStart" value="'+state.financeStart+'"></label><label>Até<input type="date" min="2026-03-01" data-key="financeEnd" value="'+state.financeEnd+'"></label>';}
else{html='<label>Entrada do lead · de<input type="date" min="2026-03-01" data-key="start" value="'+state.start+'"></label><label>Até<input type="date" min="2026-03-01" data-key="end" value="'+state.end+'"></label><label>Criativo<select data-key="ad">'+options(unique(D.meta.map(r=>r.adId)).map(id=>{const a=D.meta.find(r=>r.adId===id);return[id,a.ad+(a.ad==='SOBRADO'?' · '+id.slice(-6):'')]}),state.ad)+'</select></label>';}
if(view==='atendimento'||view==='financeiro')html+='<label>'+(view==='financeiro'?'Corretor da venda':'Responsável')+'<select data-key="broker">'+options(unique((view==='financeiro'?D.sales:D.crm).map(r=>r.broker)).sort().map(x=>[x,x]),state.broker)+'</select></label>';
if(view==='atendimento')html+='<label>Status<select data-key="status">'+options(['Aberto','Perdido','Ganho'].map(x=>[x,x]),state.status)+'</select></label>';
if(view==='atendimento'||view==='conferencia')html+='<label>Buscar nome<input type="search" data-key="query" value="'+esc(state.query)+'" placeholder="Nome do contato"></label>';
if(view==='conferencia')html+='<label>Conferência<select data-key="review">'+options([['forte','Candidatos fortes'],['nome','Nomes semelhantes'],['ausente','Não localizados']],state.review)+'</select></label>';
if(view==='historico')html+='<label>Campanha<select data-key="campaign">'+options(unique(D.history.map(r=>r.campaignId)).map(id=>[id,D.history.find(r=>r.campaignId===id).campaign]),state.campaign)+'</select></label>';
html+='<button class="btn" id="reset">Limpar filtros</button>';
$('#filters').innerHTML='<div class="filters">'+html+'</div>';
document.querySelectorAll('[data-key]').forEach(el=>el.addEventListener('change',()=>{state[el.dataset.key]=el.value;renderContent()}));
$('#reset').onclick=()=>{Object.assign(state,{start:'2026-07-27',end:'2026-09-24',ad:'',broker:'',status:'',query:'',review:'',financeStart:'2026-03-01',financeEnd:'2026-12-31',campaign:''});render()};
}
function bars(groups){const max=Math.max(1,...groups.map(g=>g.total));return '<div class="panelbody"><div class="legend"><span><i></i>Cadastros</span><span><i class="green"></i>Maior intenção</span></div>'+groups.map(g=>'<div class="barrow"><span>'+g.name+'</span><div class="bartrack"><div class="barall" style="width:'+g.total/max*100+'%"></div><div class="barhigh" style="width:'+g.high/max*100+'%"></div></div><span class="barvalue">'+g.high+' / '+g.total+' · '+pct(ratio(g.high,g.total))+'</span></div>').join('')+'</div>';}
function campaigns(){
const l=selected(),m=media(),h=l.filter(high),spend=sum(m,'spend'),n=sum(m,'leads');
let html='<div class="notice info">Casas Médio e Alto Padrão · Tijucas. Maior intenção = compra declarada em até 3 meses; ainda não é qualificação comercial confirmada.</div>';
if(state.start<'2026-07-27'||state.end>'2026-09-24')html+='<div class="notice">A base de cadastros cobre 27/07 a 24/09. Custos de maior intenção fora desse intervalo não são comparáveis; use o período completo da base.</div>';
const aligned=state.start>='2026-07-27'&&state.end<='2026-09-24';
html+='<div class="kpis">'+card('Investimento',money(spend),'Campanha selecionada',true)+card('Leads no Meta',num(n),'CPL '+money(ratio(spend,n)))+card('Maior intenção',num(h.length),pct(ratio(h.length,l.length))+' dos '+l.length+' cadastros')+card('Custo / maior intenção',aligned?money(ratio(spend,h.length)):'Não comparável',unique(h.map(r=>r.phone)).length+' telefones únicos de maior intenção')+'</div>';
const ids=unique([...m.map(r=>r.adId),...l.map(r=>r.adId)]),cr=ids.map(id=>{const a=m.filter(r=>r.adId===id),b=l.filter(r=>r.adId===id),hh=b.filter(high).length,sp=sum(a,'spend');return{id,name:(a[0]||b[0]).ad,base:b.length,hh,sp,meta:sum(a,'leads'),im:b.filter(r=>cat(r)==='Imediata').length,morn:b.filter(r=>cat(r)==='1 a 3 meses').length,cold:b.filter(r=>cat(r)==='Pesquisando').length,excluded:b.filter(r=>r.excluded).length}}).sort((a,b)=>b.hh-a.hh);
html+=panel('Criativos · custo e intenção','Contagens por cadastro. Pessoas que se cadastraram mais de uma vez podem aparecer em mais de um anúncio.',table(['Criativo','Investimento','Leads Meta','Cadastros','Imediata','1–3 meses','Pesquisando','Maior intenção','Custo / intenção'],cr.map(r=>['<b>'+esc(r.name)+'</b><small>ID '+r.id+'</small>',money(r.sp),num(r.meta),num(r.base)+(r.excluded?'<small>'+r.excluded+' fora do perfil</small>':''),r.im,r.morn,r.cold,r.hh+'<small>'+pct(ratio(r.hh,r.base))+'</small>',aligned?money(ratio(r.sp,r.hh)):'—'])));
const weekday=d=>(new Date(d+'T12:00:00Z').getUTCDay()+6)%7;
const days=['Seg','Ter','Qua','Qui','Sex','Sáb','Dom'].map((name,i)=>{const rows=l.filter(r=>weekday(r.date)===i);return{name,total:rows.length,high:rows.filter(high).length}});
const hours=['00h–05h59','06h–11h59','12h–17h59','18h–23h59'].map((name,i)=>{const rows=l.filter(r=>Math.floor(r.hour/6)===i);return{name,total:rows.length,high:rows.filter(high).length}});
html+='<div class="columns">'+panel('Dias da semana','Distribuição pela data de entrada do lead.',bars(days))+panel('Horários de entrada','Horário de São Paulo · quantidade e proporção.',bars(hours))+'</div>';
html+='<div class="notice">Não temos investimento por hora. Mais cadastros em um horário não comprovam menor custo ou maior chance de venda. Anúncios e ofertas também variam entre os períodos.</div>';
html+=panel('Como ler os números','Critérios utilizados neste protótipo.','<details><summary>Contagem, exclusões e divergências</summary><p>Os cadastros são contados pelo registro da Meta. Telefones são normalizados para deduplicação de pessoas. As duas entradas de Antonio Egon Maricato Kappel, identificado pelo usuário como corretor, permanecem no investimento e no volume, mas ficam fora da maior intenção. No intervalo original há 202 cadastros e 201 leads no Meta; o Estático 4 apresenta um registro adicional na base. Dia do resultado atribuído pelo Meta pode diferir do dia de entrada do cadastro.</p></details><details><summary>Limites para decidir investimento</summary><p>Este painel mostra associações, não prova que o criativo ou horário causou a qualidade. Compare ofertas e períodos equivalentes e confirme avanço comercial. O Estático 6 tem apenas sete cadastros na base completa. O painel não recomenda alterações automáticas de orçamento.</p></details>');
return html;
}
function attendance(){
const l=selected().filter(r=>!r.excluded),linked=l.filter(r=>r.crm.length),keys=unique(linked.flatMap(r=>r.crm)),all=D.crm.filter(r=>keys.includes(r.key));
const c=all.filter(r=>(!state.broker||r.broker===state.broker)&&(!state.status||r.status===state.status)&&r.name.toLowerCase().includes(state.query.toLowerCase()));
let html='<div class="notice info">Acompanhamento por responsável atual. Telefone coincidente vincula a pessoa; campanha e atendimento ainda precisam de confirmação. Você também atua na etapa GERENTE do follow-up.</div>';
html+='<div class="kpis">'+card('Cadastros localizados',linked.length+' / '+l.length,'Cobertura por telefone, antes dos filtros de responsável',true)+card('Atendimentos exibidos',c.length,'Pode haver mais de um por pessoa')+card('Abertos',c.filter(r=>r.status==='Aberto').length,'Situação da exportação')+card('Abertos sem atividades',c.filter(r=>r.status==='Aberto'&&r.activity==='Não').length,'Não comprova ausência de contato')+'</div>';
html+=panel('Oportunidades para acompanhar','A etapa atual não reconstrói todo o histórico. A coluna de intenção vem do formulário da Meta.',table(['Contato','Origem na base','Intenção declarada','Responsável atual','Funil / etapa','Status','Última alteração','Atividades'],c.map(r=>{const ls=linked.filter(x=>x.crm.includes(r.key));return['<b>'+esc(r.name)+'</b><small>Criado '+day(r.created)+'</small>',esc(unique(ls.map(x=>x.ad)).join(' / '))+'<small>'+esc(r.form||'Formulário ausente')+'</small>',esc(unique(ls.map(cat)).join(' / ')),esc(r.broker),esc(r.funnel)+'<small>'+esc(r.stage)+'</small>',badge(r.status,r.status==='Perdido'?'warn':'')+(r.lost?'<small>'+esc(r.lost)+'</small>':''),day(r.updated),esc(r.activity)+'<small>Registro no Praedium</small>']})));
html+='<p class="smallnote">Não usamos esses registros para um ranking de corretores. Parte da base não foi localizada; o responsável atual pode ser diferente de quem iniciou ou concluiu o atendimento.</p>';
return html;
}
function finance(){
const s=D.sales.filter(r=>r.date>=state.financeStart&&r.date<=state.financeEnd&&(!state.broker||r.broker===state.broker));
let html='<div class="notice info">Resultado geral da imobiliária. Segundo o usuário, estas vendas vieram de campanhas antigas ou Marketplace. Nenhuma está atribuída à campanha atual de Casas Tijucas.</div>';
html+='<div class="kpis">'+card('Valor dos imóveis vendidos',money(sum(s,'value')),s.length+' vendas registradas',true)+card('Comissão total registrada',money(sum(s,'commission')),'Valor informado na planilha')+card('Recebido das construtoras',money(sum(s,'received')),'Recebimento, não valor dos imóveis')+card('Saldo das construtoras',money(sum(s,'balance')),'Conforme controle financeiro')+'</div>';
html+='<div class="columns">'+panel('Participação da imobiliária','Valores da planilha, sem dedução do investimento em mídia.','<div class="panelbody"><h2>'+money(sum(s,'company'))+'</h2><p class="smallnote">Não representa lucro líquido. Repasses e outras despesas devem ser considerados separadamente.</p></div>')+panel('Comissões de Felipe','Separadas do resultado atribuído às campanhas.','<div class="panelbody"><h2>'+money(sum(s,'felipe'))+'</h2><p class="smallnote">Recebido: '+money(sum(s,'felipePaid'))+' · A receber: '+money(sum(s,'felipeBalance'))+'</p></div>')+'</div>';
html+=panel('Vendas registradas','Origem individual pendente de confirmação. Valores preservados como informados na fonte.',table(['Data','Cliente / imóvel','Corretor','Valor da venda','Comissão','Recebido','Saldo','Previsão do saldo'],s.map(r=>[day(r.date),'<b>'+esc(r.client)+'</b><small>'+esc(r.property)+'</small>',esc(r.broker),money(r.value),money(r.commission),money(r.received),money(r.balance),day(r.expected)])));
html+='<div class="notice">Não calculamos retorno das campanhas atuais usando estas vendas. A planilha de comissionamento ainda não possui telefone ou ID do Praedium para confirmar a origem de cada negócio.</div>';
return html;
}
function review(){
const ids=selected().map(r=>r.id);let a=D.audit.filter(r=>ids.includes(r.id));
const strong=a.filter(r=>r.status.startsWith('Forte')).length,similar=a.filter(r=>r.status.startsWith('Nome')).length,absent=a.length-strong-similar;
let html='<div class="kpis">'+card('Sem vínculo por telefone',a.length,'Cadastros para conferência',true)+card('Candidatos fortes',strong,'Nome, formulário e dia coincidem')+card('Nomes semelhantes',similar,'Não vinculados automaticamente')+card('Não localizados',absent,'Ausência na exportação não prova falha no atendimento')+'</div>';
html+='<div class="notice info">A investigação individual está pausada por sua escolha. Os casos ficam registrados e não impedem a análise das campanhas.</div>';
html+=panel('Conferências já esclarecidas','Evidências fornecidas pelo usuário após a exportação.','<div class="review"><span class="badge">Vínculo confirmado por histórico</span><h3>Suellen Gomes</h3><p>CASA 680 MIL · 14/08 às 13h53 · Laize Noimann. O telefone está vazio no próprio Praedium. Confirmação manual, não incorporada à cobertura automática por telefone.</p></div><div class="review"><span class="badge warn">Fora do perfil comprador</span><h3>Antonio Egon Maricato Kappel</h3><p>Duas entradas na base. Identificado pelo usuário como corretor; excluído da maior intenção neste BI. GERENTE é uma etapa do follow-up assumida por Felipe. Bases brutas preservadas.</p></div>');
if(state.review)a=a.filter(r=>state.review==='forte'?r.status.startsWith('Forte'):state.review==='nome'?r.status.startsWith('Nome'):r.status.startsWith('Não'));
a=a.filter(r=>r.name.toLowerCase().includes(state.query.toLowerCase()));
html+=panel('Lista de conferência da exportação','Situação original da auditoria; as confirmações posteriores estão destacadas acima.',table(['Nome / entrada','Criativo','Situação','Candidato no Praedium','Evidência'],a.map(r=>['<b>'+esc(r.name)+'</b><small>'+day(r.date)+'</small>',esc(r.ad),badge(r.status,r.status.startsWith('Não')?'gray':'warn'),esc(r.candidate||'—').replace(/\n/g,'<br>'),esc(r.evidence||'Sem evidência suficiente')])));
return html;
}
function renderContent(){if(state.start<'2026-03-01'||state.financeStart<'2026-03-01'){$('#content').innerHTML='<div class="notice">O painel considera apenas o período a partir de 01/03/2026.</div>';return;}if(state.start>state.end||state.financeStart>state.financeEnd){$('#content').innerHTML='<div class="notice">A data inicial deve ser anterior ou igual à data final.</div>';return;}$('#content').innerHTML=({historico:historyView,campanhas:campaigns,atendimento:attendance,financeiro:finance,conferencia:review}[view])();}
function render(){const titles={historico:['Histórico de mídia','Campanhas desde março, separadas pelo tipo de resultado.'],campanhas:['Campanhas','Investimento e intenção de compra, lado a lado.'],atendimento:['Atendimento','Onde estão as oportunidades que conseguimos localizar.'],financeiro:['Vendas e comissões','O resultado da operação, com origens separadas.'],conferencia:['Conferência','O que sabemos e o que ainda precisa de validação.']};$('#title').textContent=titles[view][0];$('#subtitle').textContent=titles[view][1];document.querySelectorAll('nav button').forEach(b=>{b.classList.toggle('active',b.dataset.view===view);b.setAttribute('aria-current',b.dataset.view===view?'page':'false')});filterUI();renderContent();}
function navigate(v){if(!['campanhas','historico','atendimento','financeiro','conferencia'].includes(v))throw new Error('Área inválida');view=v;state.broker='';state.query='';state.status='';location.hash=v;render();}
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>navigate(b.dataset.view));
Promise.all(['data.json','finance-data.json'].map(url=>fetch(url).then(r=>{if(!r.ok)throw Error('Dados indisponíveis');return r.json()}))).then(([data,fin])=>{D=data;D.fin=fin;D.sales=fin.sales;D.history=fin.history;D.leads=D.leads.filter(r=>r.date>='2026-03-01');D.meta=D.meta.filter(r=>r.date>='2026-03-01');D.history=D.history.filter(r=>r.date>='2026-03-01');D.sales=D.sales.filter(r=>r.date>='2026-03-01');const hash=location.hash.slice(1);if(['campanhas','historico','atendimento','financeiro','conferencia'].includes(hash))view=hash;render();if(document.modelContext?.registerTool){Promise.resolve(document.modelContext.registerTool({name:'filtrar_painel',description:'Abre uma área do BI e aplica um intervalo de datas. Não altera as fontes.',inputSchema:{type:'object',properties:{area:{type:'string',enum:['campanhas','historico','atendimento','financeiro','conferencia']},inicio:{type:'string'},fim:{type:'string'}},required:['area'],additionalProperties:false},execute(input){const v=input.area;if(input.inicio&&input.inicio<'2026-03-01')throw Error('O período começa em 01/03/2026');for(const d of [input.inicio,input.fim])if(d&&!/^\d{4}-\d{2}-\d{2}$/.test(d))throw Error('Use AAAA-MM-DD');if(input.inicio&&input.fim&&input.inicio>input.fim)throw Error('Intervalo inválido');if(!['campanhas','historico','atendimento','financeiro','conferencia'].includes(v))throw Error('Área inválida');if(input.inicio)state[(v==='financeiro'||v==='historico')?'financeStart':'start']=input.inicio;if(input.fim)state[(v==='financeiro'||v==='historico')?'financeEnd':'end']=input.fim;navigate(v);return{area:v,atualizacao:(v==='financeiro'||v==='historico')?D.fin.updated:D.updated};}})).catch(()=>{});}}).catch(()=>{$('#content').innerHTML='<div class="notice">Não foi possível carregar os dados. Atualize a página para tentar novamente.</div>'});

window.addEventListener('hashchange',()=>{const v=location.hash.slice(1);if(D&&v!==view&&['campanhas','historico','atendimento','financeiro','conferencia'].includes(v))navigate(v)});
