let financialTab='resultado';
const cutoff='2026-03-01', asOf='2026-10-05';
const monthKey=d=>(d||'').slice(0,7), monthName=d=>new Date(d+'-01T12:00:00Z').toLocaleDateString('pt-BR',{month:'short',year:'numeric',timeZone:'UTC'});
const saleScope=()=>D.fin.sales.filter(s=>s.date>=cutoff&&(!state.broker||s.broker===state.broker));
const period=d=>d&&d>=state.financeStart&&d<=state.financeEnd;
function monthsBetween(a,b){const out=[];let d=a.slice(0,7);while(d<=b.slice(0,7)&&out.length<120){out.push(d);const x=new Date(d+'-01T12:00:00Z');x.setUTCMonth(x.getUTCMonth()+1);d=x.toISOString().slice(0,7)}return out;}
function moneyBars(groups,keys){const max=Math.max(1,...groups.flatMap(g=>keys.map(k=>Math.abs(g[k.key]||0))));return '<div class="panelbody chart"><div class="legend">'+keys.map((k,i)=>'<span><i style="background:'+['#007b70','#7795aa','#dc9731'][i]+'"></i>'+k.label+'</span>').join('')+'</div>'+groups.map(g=>'<div class="moneyrow"><b>'+esc(g.label)+'</b><div>'+keys.map((k,i)=>'<div class="moneyline"><div class="moneytrack"><span style="width:'+Math.abs(g[k.key]||0)/max*100+'%;background:'+['#007b70','#7795aa','#dc9731'][i]+'"></span></div><span>'+money(g[k.key]||0)+'</span></div>').join('')+'</div></div>').join('')+'</div>';}

const transfersFor=(s,ps)=>sum(ps.filter(p=>p.sale===s.id&&p.broker!=='Luci'),'paid')+Number(s.trafficPaid||0)+Number(s.agentPaid||0)+Number(s.partnerPaid||0);
const retainedFor=(s,ps)=>Number(s.received||0)-transfersFor(s,ps);
function finance(){
const scope=saleScope(),sales=scope.filter(s=>period(s.date)),active=sales.filter(s=>s.status!=='Cancelada'),ids=new Set(scope.map(s=>s.id)),receipts=D.fin.receipts.filter(r=>ids.has(r.sale)),participants=D.fin.participants.filter(r=>ids.has(r.sale));
let out='<div class="notice">Base parcial · ainda faltam vendas de Luci. Comparativos provisórios. Comissões atualizadas em 05/10/2026; recebimentos sem data ficam destacados. Valores não representam lucro.</div>';
out+='<div class="subnav" role="group" aria-label="Visões financeiras">'+[['resultado','Visão geral'],['felipe','Comissões de Felipe'],['recebimentos','Recebimentos'],['previsao','Previsão de recebíveis'],['corretores','Desempenho da equipe'],['origens','Origem das vendas']].map(([k,t])=>'<button class="btn '+(financialTab===k?'selected':'')+'" data-fin="'+k+'" aria-pressed="'+(financialTab===k)+'">'+t+'</button>').join('')+'</div>';
if(financialTab==='resultado'){
const selectedIds=new Set(sales.map(s=>s.id)),ps=D.fin.participants.filter(p=>selectedIds.has(p.sale)),rs=receipts.filter(r=>selectedIds.has(r.sale));
const manager=s=>s.status==='Cancelada'?s.trafficPaid:s.traffic;
const managerTotal=sales.some(s=>manager(s)===null||manager(s)===undefined)?null:sales.reduce((t,s)=>t+Number(manager(s)||0),0);
out+='<div class="kpis">'+card('VGV total',money(sum(active,'value')),sales.length+' registros · '+active.length+' realizadas · '+(sales.length-active.length)+' '+(sales.length-active.length===1?'cancelada':'canceladas'),true)+card('Comissão total das vendas',money(sum(sales,'effective')),'Inclui recebidos preservados nas canceladas')+card('Comissão da Luci / CT',money(sum(sales,'company')),'Parte da empresa + vendas próprias de Luci')+card('Comissões dos corretores',money(sum(ps.filter(p=>p.broker!=='Luci'),'net')),'Após descontos · inclui Felipe como corretor')+card('Comissão de gerente · Felipe',managerTotal===null?'A informar':money(managerTotal),'Valor individual registrado em cada venda')+card('Comissão de corretor · Felipe',money(sum(ps.filter(p=>p.broker==='Felipe'),'net')),'Já incluída em Comissões dos corretores')+'</div>';
out+='<div class="kpis">'+card('Já recebido dessas vendas',money(sum(rs,'received')),'Entradas acumuladas, inclusive após o mês da venda')+card('Falta receber dessas vendas',money(sum(rs,'balance')),'Todo o saldo, independente do vencimento')+card('Comissão de agenciamento',money(sales.reduce((t,s)=>t+Number(s.status==='Cancelada'?s.agentPaid:s.agent),0)),'Identificação e divisão na planilha')+card('Repasses de parceria',money(sales.reduce((t,s)=>t+Number(s.status==='Cancelada'?s.partnerPaid:s.partner),0)),'Participação de imobiliárias parceiras')+'</div>';
out+=luciCashPanel(sales);
const groups=monthsBetween(state.financeStart,state.financeEnd).map(m=>{const s=sales.filter(s=>monthKey(s.date)===m),ids=new Set(s.map(s=>s.id));return{label:monthName(m),ct:sum(s,'company'),brokers:sum(ps.filter(p=>ids.has(p.sale)&&p.broker!=='Luci'),'net'),manager:s.reduce((t,s)=>t+Number(manager(s)||0),0)}});
out+=panel('Comissões por mês da venda','Distribuição das comissões. Recebimentos são acompanhados separadamente pela data de entrada.',moneyBars(groups,[{key:'ct',label:'Luci / Conhecendo Tijucas'},{key:'brokers',label:'Corretores · após descontos'},{key:'manager',label:'Gerente · Felipe'}]));
out+=panel('Vendas realizadas','Pendências de origem ou cadastro não tornam a venda uma previsão. Canceladas ficam fora do VGV.',table(['Venda','Corretor da venda','Situação','VGV','Comissão total','Luci / CT','Gerente · Felipe','Recebido','A receber'],sales.map(s=>['<b>'+esc(s.client)+'</b><small>'+day(s.date)+' · '+esc(s.property)+'</small>',esc(s.broker),badge(s.status==='Cancelada'?'Cancelada':'Realizada',s.status==='Cancelada'?'warn':'gray'),s.status==='Cancelada'?'—':money(s.value),money(s.effective),money(s.company),manager(s)==null?'A informar':money(manager(s)),money(s.received),money(s.balance)])));
out+=panel('Divisão da comissão por venda','As partes somam a comissão total. Luci e CT são uma única parte; sua comissão não é contada novamente como corretora.',table(['Venda / corretor','Comissão total','Luci / CT','Corretores após descontos','Gerente','Agenciador','Parceria'],sales.map(s=>[esc(s.client)+'<small>'+esc(s.broker)+'</small>',money(s.effective),money(s.company),money(sum(ps.filter(p=>p.sale===s.id&&p.broker!=='Luci'),'net')),manager(s)==null?'A informar':money(manager(s)),money(s.status==='Cancelada'?s.agentPaid:s.agent),money(s.status==='Cancelada'?s.partnerPaid:s.partner)])));
out+=panel('Pagamentos dos participantes dessas vendas','Valores acumulados registrados na base, independente do mês de pagamento. Uma entrada da venda não marca os repasses como pagos.',table(['Participante','Comissão','Já pago','Falta pagar'],[['Gerente · Felipe',managerTotal===null?'A informar':money(managerTotal),money(sum(sales,'trafficPaid')),managerTotal===null?'A informar':money(Math.max(0,managerTotal-sum(sales,'trafficPaid')))],['Agenciador',money(sales.reduce((t,s)=>t+Number(s.status==='Cancelada'?s.agentPaid:s.agent),0)),money(sum(sales,'agentPaid')),money(sales.reduce((t,s)=>t+(s.status==='Cancelada'?0:Math.max(0,Number(s.agent)-Number(s.agentPaid))),0))],['Parceria',money(sales.reduce((t,s)=>t+Number(s.status==='Cancelada'?s.partnerPaid:s.partner),0)),money(sum(sales,'partnerPaid')),money(sales.reduce((t,s)=>t+(s.status==='Cancelada'?0:Math.max(0,Number(s.partner)-Number(s.partnerPaid))),0))],...unique(ps.filter(p=>p.broker!=='Luci').map(p=>p.broker)).map(b=>{const rows=ps.filter(p=>p.broker===b);return[esc(b)+' · corretor',money(sum(rows,'net')),money(sum(rows,'paid')),money(sum(rows,'balance'))]})]));
out+=panel('Cobertura dos dados','Ainda faltam vendas de Luci. Valores zerados não comprovam ausência de vendas.',table(['Mês','Conferência da base'],monthsBetween(state.financeStart,state.financeEnd).map(m=>[monthName(m),esc(D.fin.coverage.find(c=>c.month===m)?.status||'Sem confirmação')])));
out+='<p class="smallnote">Comissão total é o total antes da divisão; não deve ser somada novamente às partes dos participantes. Valores de comissão não representam lucro.</p>';
}
if(financialTab==='felipe'){
const fsales=D.fin.sales.filter(s=>s.date>=cutoff&&period(s.date)),fids=new Set(fsales.map(s=>s.id)),fp=D.fin.participants.filter(p=>p.broker==='Felipe'&&fids.has(p.sale)),mgr=fsales.filter(s=>Number(s.traffic)>0||Number(s.trafficPaid)>0||s.traffic==null),amount=s=>s.status==='Cancelada'?s.trafficPaid:s.traffic;
out+='<div class="notice info">O período usa o mês da venda. Esta visão reúne suas comissões em todas as vendas, independente do filtro Corretor da venda. Recebidos e saldos são os valores acumulados registrados na planilha.</div>';
out+='<div class="columns felipe-panels">'+panel('Felipe · gerente','Comissão negociada em cada venda.','<div class="kpis">'+card('Comissão de gerente',mgr.some(s=>amount(s)==null)?'A informar':money(mgr.reduce((t,s)=>t+Number(amount(s)||0),0)),'Valores da planilha',true)+card('Já recebido',money(sum(mgr,'trafficPaid')),'Pagamentos ao gerente')+card('Falta receber',money(sum(mgr,'managerBalance')),'Saldo registrado')+'</div>')+panel('Felipe · corretor','Sua participação nas vendas como corretor.','<div class="kpis">'+card('Comissão de corretor',money(sum(fp,'net')),'Após descontos · inclui cancelamentos realizados',true)+card('Já recebido',money(sum(fp,'paid')),'Repasses ao corretor')+card('Falta receber',money(sum(fp,'balance')),'Saldo registrado')+'</div>')+'</div>';
out+=panel('Comissões de gerente por venda','Datas de vencimento e pagamentos informadas manualmente.',table(['Cliente','Corretor da venda','Comissão de gerente','Recebido','Saldo','Vencimento','Último pagamento'],mgr.map(s=>[esc(s.client),esc(s.broker),amount(s)==null?'A informar':money(amount(s)),money(s.trafficPaid),money(s.managerBalance),s.status==='Cancelada'?'—':day(s.managerDue),day(s.managerPaidDate)])));
out+=panel('Comissões de corretor por venda','Esta comissão compõe o total da equipe. Sua comissão de gerente é uma remuneração adicional, quando registrada.',table(['Cliente','Comissão de corretor','Recebido','Saldo','Vencimento','Último pagamento'],fp.map(p=>{const s=fsales.find(s=>s.id===p.sale);return[esc(s.client),money(p.net),money(p.paid),money(p.balance),s.status==='Cancelada'?'—':day(p.due),day(p.paidDate)]})));
}
if(financialTab==='recebimentos'){
const cohort=scope.filter(s=>period(s.date)),cids=new Set(cohort.map(s=>s.id)),cp=participants.filter(p=>cids.has(p.sale)),cr=receipts.filter(r=>cids.has(r.sale));
out+='<div class="notice info">Resumo das vendas fechadas no período: entradas acumuladas e repasses já realizados, mesmo em meses posteriores. O gráfico abaixo usa as datas efetivas de recebimento.</div>';
out+=cashDistribution(cohort,cp);
const entered=receipts.filter(r=>period(r.date)),due=receipts.filter(r=>period(r.due)&&r.balance>0),missing=receipts.filter(r=>r.received>0&&!r.date);
out+=panel('Entradas por mês e vencimentos','Este bloco usa as datas das parcelas de todas as vendas do corretor selecionado. Recebimentos sem data ficam fora dos meses.','<div class="kpis">'+card('Entradas com data no período',money(sum(entered,'received')),'Data efetiva do recebimento')+card('Recebido sem data',money(sum(missing,'received')),'Aguardando data para distribuição mensal')+card('Saldo vencido no período',money(sum(due.filter(r=>r.due<asOf),'balance')),'Posição em '+day(asOf))+'</div>'+moneyBars(monthsBetween(state.financeStart,state.financeEnd).map(m=>({label:monthName(m),received:sum(entered.filter(r=>monthKey(r.date)===m),'received'),balance:sum(due.filter(r=>monthKey(r.due)===m),'balance')})),[{key:'received',label:'Dinheiro que entrou'},{key:'balance',label:'Saldo por vencimento'}]));
out+=panel('Parcelas a receber','Vencimentos manuais. Valores após o período continuam visíveis no detalhamento das vendas selecionadas.',table(['Cliente','Vencimento','Saldo','Situação'],cr.filter(r=>r.balance>0).map(r=>[esc(r.client),day(r.due),money(r.balance),r.due&&r.due<asOf?badge('Vencido','warn'):badge(r.due?'A receber':'Sem vencimento','gray')])));
out+='<p class="smallnote">Recebido a distribuir é o dinheiro cuja destinação ainda não foi completamente registrada. A parte da Luci só entra como recebida quando preenchida na planilha.</p>';
}
if(financialTab==='previsao'){out+=forecastView();}
if(financialTab==='corretores'){
const aids=new Set(active.map(s=>s.id)),ps=D.fin.participants.filter(p=>aids.has(p.sale));
const groups=unique(ps.map(p=>p.broker)).map(b=>{const rs=ps.filter(p=>p.broker===b);return{label:b,count:sum(rs,'credit'),value:sum(rs,'value'),ct:sum(rs,'ct'),net:sum(rs,'net')}}).sort((a,b)=>b.ct-a.ct);
out+='<div class="notice info">Comparação provisória para acompanhar resultados. Luci é proprietária e corretora: sua participação é diferente. A base incompleta não sustenta uma premiação definitiva.</div>';
out+=panel('Contribuição da equipe para a CT','Registros não cancelados do período. Em vendas compartilhadas, utiliza o crédito registrado na planilha.',moneyBars(groups.filter(g=>g.label!=='Luci'),[{key:'ct',label:'Comissão gerada para a CT'}]));
out+=panel('Produção da equipe · inclui Luci','Compare vendas e VGV. A coluna de comissão CT/Luci tem uma participação diferente nas vendas próprias da Luci.',table(['Corretor','Vendas equivalentes','Valor vendido atribuído','Comissão da Luci / CT','Comissão após descontos'],groups.map(g=>['<b>'+esc(g.label)+'</b>'+(g.label==='Luci'?'<small>Proprietária e corretora</small>':''),g.count,money(g.value),money(g.ct),money(g.net)])));
out+='<p class="smallnote">Todas as vendas não canceladas são realizadas. A confirmação da origem é um controle separado.</p>'; 
}
if(financialTab==='origens'){
const origins=unique(active.map(s=>s.origin||'Não identificada'));
out+=panel('De onde vieram os compradores','Vendas e comissão total gerada por origem informada na planilha.',table(['Origem','Vendas não canceladas','Valor vendido','Comissão total gerada'],origins.map(o=>{const rs=active.filter(s=>(s.origin||'Não identificada')===o);return[esc(o),rs.length,money(sum(rs,'value')),money(sum(rs,'commission'))]})));
out+=panel('Vínculos informados','Origem e campanha informadas para cada venda.',table(['Comprador','Origem','Campanha','Situação'],sales.map(s=>[esc(s.client),esc(s.origin),esc(s.campaign||'Não identificada'),esc(s.status==='Cancelada'?'Cancelada':'Realizada')])));
}
return out;}
document.addEventListener('click',e=>{const b=e.target.closest('[data-fin]');if(b){financialTab=b.dataset.fin;filterUI();renderContent();}});
