function historyView(){
const all=D.history.filter(r=>r.date>=state.financeStart&&r.date<=state.financeEnd&&(!state.campaign||r.campaignId===state.campaign));
const sp=sum(all,'spend'),im=sum(all,'impressions'),cl=sum(all,'clicks');
let html='<div class="notice info">Relatório do Meta de 01/03 a 26/09/2026. Campanhas de formulário, WhatsApp e engajamento têm resultados diferentes. Não somamos essas ações como se fossem leads únicos.</div><div class="kpis">'+card('Investimento histórico',money(sp),'Todas as campanhas do filtro',true)+card('Campanhas',unique(all.map(r=>r.campaignId)).length,'Resultados separados por objetivo')+card('Impressões',num(im),'Exibições, não pessoas únicas')+card('Cliques no link',num(cl),'CPC '+money(ratio(sp,cl)))+'</div>';
html+=panel('Investimento por mês','Histórico disponível desde março de 2026.',moneyBars(monthsBetween(state.financeStart,state.financeEnd).map(m=>({label:monthName(m),spend:sum(all.filter(r=>monthKey(r.date)===m),'spend')})),[{key:'spend',label:'Investimento em mídia'}]));
const groups=unique(all.map(r=>r.campaignId)).map(id=>{const rs=all.filter(r=>r.campaignId===id);const types=unique(rs.filter(r=>r.results).map(r=>r.resultType));return{rs,sp:sum(rs,'spend'),types,id,name:rs[0].campaign}}).sort((a,b)=>b.sp-a.sp);
html+=panel('Campanhas anteriores e atuais','Conversas iniciadas não equivalem a pessoas únicas nem a vendas confirmadas.',table(['Campanha','Investimento','Resultados reportados','Custo por resultado','Vendas atribuídas'],groups.map(g=>{const text=g.types.map(t=>esc(t)+': <b>'+num(sum(g.rs.filter(r=>r.resultType===t),'results'))+'</b>').join('<br>');return['<b>'+esc(g.name)+'</b><small>ID '+g.id+'</small>',money(g.sp),text||'Sem resultado registrado',g.types.length===1?money(ratio(g.sp,sum(g.rs,'results'))):'—',badge('Não confirmado','gray')]})));
const linked=D.fin.sales.filter(s=>period(s.date)&&s.origin==='Meta Ads');
html+=panel('Vendas com origem Meta Ads informada','Contexto comercial no período de venda selecionado, independente do filtro de campanha de mídia. Nomes informados na planilha ainda não vinculados por ID ao Meta.',table(['Comprador','Campanha informada','Data da venda','Confirmação da origem','Situação','Resultado CT / Luci'],linked.map(s=>[esc(s.client),esc(s.campaign||'Não identificada'),day(s.date),esc(s.confirmed),badge(s.status,s.status==='Cancelada'?'warn':'gray'),money(s.company)])));
html+='<div class="notice">O histórico mostra o investimento e os resultados disponíveis. As vendas informadas como Villa Mar aparecem acima, mas a base comercial ainda está incompleta. Não calculamos ROI nem atribuímos essas vendas automaticamente a um anúncio. A ausência de vínculo não significa ausência de venda.</div>';
html+=panel('Como fechar o retorno','A confirmação da origem vem antes do cálculo.','<div class="panelbody"><p>Após confirmar os vínculos, podemos comparar investimento com comissão gerada e comissão recebida, respeitando o tempo entre a campanha e a venda.</p><p class="smallnote">O valor total dos imóveis vendidos não é receita da imobiliária. Retorno sobre comissão também não representa lucro líquido sem considerar as demais despesas.</p></div>');
return html;
}
